// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from "@hey-api/client-fetch";

import { client as _heyApiClient } from "./client.gen";
import type {
  GetPaywallApiPaywallGetData,
  GetPaywallApiPaywallGetErrors,
  GetPaywallApiPaywallGetResponses,
  ListAccountsApiAccountsGetData,
  ListAccountsApiAccountsGetErrors,
  ListAccountsApiAccountsGetResponses,
  ListPricesApiPricesGetData,
  ListPricesApiPricesGetErrors,
  ListPricesApiPricesGetResponses,
  ListQuotasApiQuotasGetData,
  ListQuotasApiQuotasGetErrors,
  ListQuotasApiQuotasGetResponses,
  ListSubscriptionsApiSubscriptionsGetData,
  ListSubscriptionsApiSubscriptionsGetErrors,
  ListSubscriptionsApiSubscriptionsGetResponses,
  ListUpgradesApiUpgradesGetData,
  ListUpgradesApiUpgradesGetErrors,
  ListUpgradesApiUpgradesGetResponses,
  ListUsageEventsApiUsageEventsGetData,
  ListUsageEventsApiUsageEventsGetErrors,
  ListUsageEventsApiUsageEventsGetResponses,
  ListUsagesApiUsagesGetData,
  ListUsagesApiUsagesGetErrors,
  ListUsagesApiUsagesGetResponses,
  OpenCheckoutApiCheckoutGetData,
  OpenCheckoutApiCheckoutGetErrors,
  OpenCheckoutApiCheckoutGetResponses,
  OpenCustomerPortalApiCustomerPortalGetData,
  OpenCustomerPortalApiCustomerPortalGetErrors,
  OpenCustomerPortalApiCustomerPortalGetResponses,
  ReportMeterEventsApiMeterEventsPostData,
  ReportMeterEventsApiMeterEventsPostErrors,
  ReportMeterEventsApiMeterEventsPostResponses,
  UpsertAccountApiAccountsPutData,
  UpsertAccountApiAccountsPutErrors,
  UpsertAccountApiAccountsPutResponses,
  UpsertPriceApiPricesPutData,
  UpsertPriceApiPricesPutErrors,
  UpsertPriceApiPricesPutResponses,
  UpsertQuotaApiQuotasPutData,
  UpsertQuotaApiQuotasPutErrors,
  UpsertQuotaApiQuotasPutResponses,
  UpsertSubscriptionApiSubscriptionsPutData,
  UpsertSubscriptionApiSubscriptionsPutErrors,
  UpsertSubscriptionApiSubscriptionsPutResponses,
  UpsertUpgradeApiUpgradesPutData,
  UpsertUpgradeApiUpgradesPutErrors,
  UpsertUpgradeApiUpgradesPutResponses,
  UpsertUsageEventApiUsageEventsPostData,
  UpsertUsageEventApiUsageEventsPostErrors,
  UpsertUsageEventApiUsageEventsPostResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List Accounts
 */
export const listAccountsApiAccountsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAccountsApiAccountsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAccountsApiAccountsGetResponses,
    ListAccountsApiAccountsGetErrors,
    ThrowOnError
  >({
    url: "/api/accounts",
    ...options,
  });
};

/**
 * Upsert Account
 */
export const upsertAccountApiAccountsPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpsertAccountApiAccountsPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpsertAccountApiAccountsPutResponses,
    UpsertAccountApiAccountsPutErrors,
    ThrowOnError
  >({
    url: "/api/accounts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Open Checkout
 */
export const openCheckoutApiCheckoutGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OpenCheckoutApiCheckoutGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    OpenCheckoutApiCheckoutGetResponses,
    OpenCheckoutApiCheckoutGetErrors,
    ThrowOnError
  >({
    url: "/api/checkout",
    ...options,
  });
};

/**
 * Open Customer Portal
 */
export const openCustomerPortalApiCustomerPortalGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OpenCustomerPortalApiCustomerPortalGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    OpenCustomerPortalApiCustomerPortalGetResponses,
    OpenCustomerPortalApiCustomerPortalGetErrors,
    ThrowOnError
  >({
    url: "/api/customer-portal",
    ...options,
  });
};

/**
 * Report Meter Events
 */
export const reportMeterEventsApiMeterEventsPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReportMeterEventsApiMeterEventsPostData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    ReportMeterEventsApiMeterEventsPostResponses,
    ReportMeterEventsApiMeterEventsPostErrors,
    ThrowOnError
  >({
    url: "/api/meter-events",
    ...options,
  });
};

/**
 * Get Paywall
 */
export const getPaywallApiPaywallGet = <ThrowOnError extends boolean = false>(
  options: Options<GetPaywallApiPaywallGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPaywallApiPaywallGetResponses,
    GetPaywallApiPaywallGetErrors,
    ThrowOnError
  >({
    url: "/api/paywall",
    ...options,
  });
};

/**
 * List Prices
 */
export const listPricesApiPricesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListPricesApiPricesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListPricesApiPricesGetResponses,
    ListPricesApiPricesGetErrors,
    ThrowOnError
  >({
    url: "/api/prices",
    ...options,
  });
};

/**
 * Upsert Price
 */
export const upsertPriceApiPricesPut = <ThrowOnError extends boolean = false>(
  options: Options<UpsertPriceApiPricesPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpsertPriceApiPricesPutResponses,
    UpsertPriceApiPricesPutErrors,
    ThrowOnError
  >({
    url: "/api/prices",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Quotas
 */
export const listQuotasApiQuotasGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListQuotasApiQuotasGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListQuotasApiQuotasGetResponses,
    ListQuotasApiQuotasGetErrors,
    ThrowOnError
  >({
    url: "/api/quotas",
    ...options,
  });
};

/**
 * Upsert Quota
 */
export const upsertQuotaApiQuotasPut = <ThrowOnError extends boolean = false>(
  options: Options<UpsertQuotaApiQuotasPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpsertQuotaApiQuotasPutResponses,
    UpsertQuotaApiQuotasPutErrors,
    ThrowOnError
  >({
    url: "/api/quotas",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Subscriptions
 */
export const listSubscriptionsApiSubscriptionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListSubscriptionsApiSubscriptionsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListSubscriptionsApiSubscriptionsGetResponses,
    ListSubscriptionsApiSubscriptionsGetErrors,
    ThrowOnError
  >({
    url: "/api/subscriptions",
    ...options,
  });
};

/**
 * Upsert Subscription
 */
export const upsertSubscriptionApiSubscriptionsPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpsertSubscriptionApiSubscriptionsPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpsertSubscriptionApiSubscriptionsPutResponses,
    UpsertSubscriptionApiSubscriptionsPutErrors,
    ThrowOnError
  >({
    url: "/api/subscriptions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Usages
 */
export const listUsagesApiUsagesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsagesApiUsagesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListUsagesApiUsagesGetResponses,
    ListUsagesApiUsagesGetErrors,
    ThrowOnError
  >({
    url: "/api/usages",
    ...options,
  });
};

/**
 * List Usage Events
 */
export const listUsageEventsApiUsageEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUsageEventsApiUsageEventsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListUsageEventsApiUsageEventsGetResponses,
    ListUsageEventsApiUsageEventsGetErrors,
    ThrowOnError
  >({
    url: "/api/usage-events",
    ...options,
  });
};

/**
 * Upsert Usage Event
 */
export const upsertUsageEventApiUsageEventsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpsertUsageEventApiUsageEventsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    UpsertUsageEventApiUsageEventsPostResponses,
    UpsertUsageEventApiUsageEventsPostErrors,
    ThrowOnError
  >({
    url: "/api/usage-events",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Upgrades
 */
export const listUpgradesApiUpgradesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListUpgradesApiUpgradesGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListUpgradesApiUpgradesGetResponses,
    ListUpgradesApiUpgradesGetErrors,
    ThrowOnError
  >({
    url: "/api/upgrades",
    ...options,
  });
};

/**
 * Upsert Upgrade
 */
export const upsertUpgradeApiUpgradesPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpsertUpgradeApiUpgradesPutData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpsertUpgradeApiUpgradesPutResponses,
    UpsertUpgradeApiUpgradesPutErrors,
    ThrowOnError
  >({
    url: "/api/upgrades",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
