// This file is auto-generated by @hey-api/openapi-ts

/**
 * Account
 * A billing account.
 */
export type Account = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Domains
   */
  domains?: Array<string>;
  /**
   * Id
   */
  id?: string;
  /**
   * Members
   */
  members?: Array<string>;
  /**
   * Name
   */
  name: string;
  /**
   * Owner
   */
  owner: string;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Stripe Customer Id
   */
  stripe_customer_id?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Metric
 * A usage-based billing metric.
 */
export type Metric = "projects_created" | "revisions_generated";

/**
 * Paywall
 */
export type Paywall = {
  /**
   * Recommended Upgrades
   */
  recommended_upgrades: Array<RecommendedUpgrade>;
};

/**
 * Period
 * A time interval.
 */
export type Period = {
  /**
   * Starts At
   */
  starts_at: string;
  /**
   * Ends At
   */
  ends_at: string;
};

/**
 * Price
 * A price of a subscription.
 */
export type Price = {
  /**
   * Amount
   */
  amount?: number;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Currency
   */
  currency?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Id
   */
  id?: string;
  /**
   * Stripe Price Id
   */
  stripe_price_id: string;
  /**
   * Stripe Product Id
   */
  stripe_product_id?: string;
};

/**
 * Quota
 * A usage limit.
 */
export type Quota = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Hard Limit
   */
  hard_limit?: number | null;
  /**
   * Id
   */
  id?: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  metric: Metric;
  /**
   * Price Id
   */
  price_id: string;
  /**
   * Soft Limit
   */
  soft_limit?: number | null;
};

/**
 * RecommendedUpgrade
 */
export type RecommendedUpgrade = {
  current_usage: Usage;
  upgrade: Upgrade;
  upgrade_price: Price;
  /**
   * Upgrade Quotas
   */
  upgrade_quotas: Array<Quota>;
};

/**
 * Subscription
 * A paid subscription.
 */
export type Subscription = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Billing Periods
   */
  billing_periods: Array<Period>;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Id
   */
  id?: string;
  /**
   * Price Id
   */
  price_id: string;
  /**
   * Status
   */
  status?:
    | "active"
    | "canceled"
    | "incomplete"
    | "incomplete_expired"
    | "past_due"
    | "paused"
    | "trialing"
    | "unpaid";
  /**
   * Stripe Subscription Id
   */
  stripe_subscription_id: string;
  /**
   * Stripe Subscription Item Id
   */
  stripe_subscription_item_id: string;
};

/**
 * Upgrade
 * A suggested upgrade from one price to another.
 */
export type Upgrade = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Current Price Id
   */
  current_price_id?: string | null;
  /**
   * Id
   */
  id?: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Upgrade Price Id
   */
  upgrade_price_id: string;
};

/**
 * Usage
 * Amount of a quota that has been used.
 */
export type Usage = {
  account: Account;
  billing_period: Period;
  metric: Metric;
  price: Price;
  quota: Quota | null;
  subscription: Subscription;
  /**
   * Usage
   */
  usage: number;
};

/**
 * UsageEvent
 * A billable event.
 */
export type UsageEvent = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: string;
  metric: Metric;
  /**
   * Subscription Id
   */
  subscription_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ListAccountsApiAccountsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Stripe Customer Id
     */
    stripe_customer_id?: string | null;
  };
  url: "/api/accounts";
};

export type ListAccountsApiAccountsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAccountsApiAccountsGetError =
  ListAccountsApiAccountsGetErrors[keyof ListAccountsApiAccountsGetErrors];

export type ListAccountsApiAccountsGetResponses = {
  /**
   * Response List Accounts Api Accounts Get
   * Successful Response
   */
  200: Array<Account>;
};

export type ListAccountsApiAccountsGetResponse =
  ListAccountsApiAccountsGetResponses[keyof ListAccountsApiAccountsGetResponses];

export type UpsertAccountApiAccountsPutData = {
  body: Account;
  path?: never;
  query?: never;
  url: "/api/accounts";
};

export type UpsertAccountApiAccountsPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertAccountApiAccountsPutError =
  UpsertAccountApiAccountsPutErrors[keyof UpsertAccountApiAccountsPutErrors];

export type UpsertAccountApiAccountsPutResponses = {
  /**
   * Successful Response
   */
  200: Account;
};

export type UpsertAccountApiAccountsPutResponse =
  UpsertAccountApiAccountsPutResponses[keyof UpsertAccountApiAccountsPutResponses];

export type OpenCheckoutApiCheckoutGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Cancel Url
     */
    cancel_url: string;
    /**
     * Price Id
     */
    price_id: string;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Success Url
     */
    success_url: string;
  };
  url: "/api/checkout";
};

export type OpenCheckoutApiCheckoutGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpenCheckoutApiCheckoutGetError =
  OpenCheckoutApiCheckoutGetErrors[keyof OpenCheckoutApiCheckoutGetErrors];

export type OpenCheckoutApiCheckoutGetResponses = {
  /**
   * Response Open Checkout Api Checkout Get
   * Successful Response
   */
  200: string;
};

export type OpenCheckoutApiCheckoutGetResponse =
  OpenCheckoutApiCheckoutGetResponses[keyof OpenCheckoutApiCheckoutGetResponses];

export type OpenCustomerPortalApiCustomerPortalGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Return Url
     */
    return_url: string;
  };
  url: "/api/customer-portal";
};

export type OpenCustomerPortalApiCustomerPortalGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpenCustomerPortalApiCustomerPortalGetError =
  OpenCustomerPortalApiCustomerPortalGetErrors[keyof OpenCustomerPortalApiCustomerPortalGetErrors];

export type OpenCustomerPortalApiCustomerPortalGetResponses = {
  /**
   * Response Open Customer Portal Api Customer Portal Get
   * Successful Response
   */
  200: string;
};

export type OpenCustomerPortalApiCustomerPortalGetResponse =
  OpenCustomerPortalApiCustomerPortalGetResponses[keyof OpenCustomerPortalApiCustomerPortalGetResponses];

export type ReportMeterEventsApiMeterEventsPostData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Subscription Id
     */
    subscription_id?: string | null;
  };
  url: "/api/meter-events";
};

export type ReportMeterEventsApiMeterEventsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReportMeterEventsApiMeterEventsPostError =
  ReportMeterEventsApiMeterEventsPostErrors[keyof ReportMeterEventsApiMeterEventsPostErrors];

export type ReportMeterEventsApiMeterEventsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPaywallApiPaywallGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Email
     */
    email: string;
  };
  url: "/api/paywall";
};

export type GetPaywallApiPaywallGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPaywallApiPaywallGetError =
  GetPaywallApiPaywallGetErrors[keyof GetPaywallApiPaywallGetErrors];

export type GetPaywallApiPaywallGetResponses = {
  /**
   * Response Get Paywall Api Paywall Get
   * Successful Response
   */
  200: Paywall | null;
};

export type GetPaywallApiPaywallGetResponse =
  GetPaywallApiPaywallGetResponses[keyof GetPaywallApiPaywallGetResponses];

export type ListPricesApiPricesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Stripe Price Id
     */
    stripe_price_id?: string | null;
    /**
     * Stripe Product Id
     */
    stripe_product_id?: string | null;
  };
  url: "/api/prices";
};

export type ListPricesApiPricesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListPricesApiPricesGetError =
  ListPricesApiPricesGetErrors[keyof ListPricesApiPricesGetErrors];

export type ListPricesApiPricesGetResponses = {
  /**
   * Response List Prices Api Prices Get
   * Successful Response
   */
  200: Array<Price>;
};

export type ListPricesApiPricesGetResponse =
  ListPricesApiPricesGetResponses[keyof ListPricesApiPricesGetResponses];

export type UpsertPriceApiPricesPutData = {
  body: Price;
  path?: never;
  query?: never;
  url: "/api/prices";
};

export type UpsertPriceApiPricesPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertPriceApiPricesPutError =
  UpsertPriceApiPricesPutErrors[keyof UpsertPriceApiPricesPutErrors];

export type UpsertPriceApiPricesPutResponses = {
  /**
   * Successful Response
   */
  200: Price;
};

export type UpsertPriceApiPricesPutResponse =
  UpsertPriceApiPricesPutResponses[keyof UpsertPriceApiPricesPutResponses];

export type ListQuotasApiQuotasGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Account Id
     */
    account_id?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Metric
     */
    metric?: Metric | null;
  };
  url: "/api/quotas";
};

export type ListQuotasApiQuotasGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListQuotasApiQuotasGetError =
  ListQuotasApiQuotasGetErrors[keyof ListQuotasApiQuotasGetErrors];

export type ListQuotasApiQuotasGetResponses = {
  /**
   * Response List Quotas Api Quotas Get
   * Successful Response
   */
  200: Array<Quota>;
};

export type ListQuotasApiQuotasGetResponse =
  ListQuotasApiQuotasGetResponses[keyof ListQuotasApiQuotasGetResponses];

export type UpsertQuotaApiQuotasPutData = {
  body: Quota;
  path?: never;
  query?: never;
  url: "/api/quotas";
};

export type UpsertQuotaApiQuotasPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertQuotaApiQuotasPutError =
  UpsertQuotaApiQuotasPutErrors[keyof UpsertQuotaApiQuotasPutErrors];

export type UpsertQuotaApiQuotasPutResponses = {
  /**
   * Successful Response
   */
  200: Quota;
};

export type UpsertQuotaApiQuotasPutResponse =
  UpsertQuotaApiQuotasPutResponses[keyof UpsertQuotaApiQuotasPutResponses];

export type ListSubscriptionsApiSubscriptionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Account Id
     */
    account_id?: string | null;
    /**
     * Stripe Subscription Id
     */
    stripe_subscription_id?: string | null;
    /**
     * Stripe Subscription Item Id
     */
    stripe_subscription_item_id?: string | null;
  };
  url: "/api/subscriptions";
};

export type ListSubscriptionsApiSubscriptionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSubscriptionsApiSubscriptionsGetError =
  ListSubscriptionsApiSubscriptionsGetErrors[keyof ListSubscriptionsApiSubscriptionsGetErrors];

export type ListSubscriptionsApiSubscriptionsGetResponses = {
  /**
   * Response List Subscriptions Api Subscriptions Get
   * Successful Response
   */
  200: Array<Subscription>;
};

export type ListSubscriptionsApiSubscriptionsGetResponse =
  ListSubscriptionsApiSubscriptionsGetResponses[keyof ListSubscriptionsApiSubscriptionsGetResponses];

export type UpsertSubscriptionApiSubscriptionsPutData = {
  body: Subscription;
  path?: never;
  query?: never;
  url: "/api/subscriptions";
};

export type UpsertSubscriptionApiSubscriptionsPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertSubscriptionApiSubscriptionsPutError =
  UpsertSubscriptionApiSubscriptionsPutErrors[keyof UpsertSubscriptionApiSubscriptionsPutErrors];

export type UpsertSubscriptionApiSubscriptionsPutResponses = {
  /**
   * Successful Response
   */
  200: Subscription;
};

export type UpsertSubscriptionApiSubscriptionsPutResponse =
  UpsertSubscriptionApiSubscriptionsPutResponses[keyof UpsertSubscriptionApiSubscriptionsPutResponses];

export type ListUsagesApiUsagesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Account Id
     */
    account_id?: string | null;
    /**
     * As Of
     */
    as_of?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Metric
     */
    metric?: Metric | null;
  };
  url: "/api/usages";
};

export type ListUsagesApiUsagesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUsagesApiUsagesGetError =
  ListUsagesApiUsagesGetErrors[keyof ListUsagesApiUsagesGetErrors];

export type ListUsagesApiUsagesGetResponses = {
  /**
   * Response List Usages Api Usages Get
   * Successful Response
   */
  200: Array<Usage>;
};

export type ListUsagesApiUsagesGetResponse =
  ListUsagesApiUsagesGetResponses[keyof ListUsagesApiUsagesGetResponses];

export type ListUsageEventsApiUsageEventsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Metric
     */
    metric?: Metric | null;
    /**
     * Subscription Id
     */
    subscription_id?: string | null;
  };
  url: "/api/usage-events";
};

export type ListUsageEventsApiUsageEventsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUsageEventsApiUsageEventsGetError =
  ListUsageEventsApiUsageEventsGetErrors[keyof ListUsageEventsApiUsageEventsGetErrors];

export type ListUsageEventsApiUsageEventsGetResponses = {
  /**
   * Response List Usage Events Api Usage Events Get
   * Successful Response
   */
  200: Array<UsageEvent>;
};

export type ListUsageEventsApiUsageEventsGetResponse =
  ListUsageEventsApiUsageEventsGetResponses[keyof ListUsageEventsApiUsageEventsGetResponses];

export type UpsertUsageEventApiUsageEventsPostData = {
  body: UsageEvent;
  path?: never;
  query?: never;
  url: "/api/usage-events";
};

export type UpsertUsageEventApiUsageEventsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertUsageEventApiUsageEventsPostError =
  UpsertUsageEventApiUsageEventsPostErrors[keyof UpsertUsageEventApiUsageEventsPostErrors];

export type UpsertUsageEventApiUsageEventsPostResponses = {
  /**
   * Successful Response
   */
  200: UsageEvent;
};

export type UpsertUsageEventApiUsageEventsPostResponse =
  UpsertUsageEventApiUsageEventsPostResponses[keyof UpsertUsageEventApiUsageEventsPostResponses];

export type ListUpgradesApiUpgradesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Stripe Product Id
     */
    stripe_product_id?: string | null;
  };
  url: "/api/upgrades";
};

export type ListUpgradesApiUpgradesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListUpgradesApiUpgradesGetError =
  ListUpgradesApiUpgradesGetErrors[keyof ListUpgradesApiUpgradesGetErrors];

export type ListUpgradesApiUpgradesGetResponses = {
  /**
   * Response List Upgrades Api Upgrades Get
   * Successful Response
   */
  200: Array<Upgrade>;
};

export type ListUpgradesApiUpgradesGetResponse =
  ListUpgradesApiUpgradesGetResponses[keyof ListUpgradesApiUpgradesGetResponses];

export type UpsertUpgradeApiUpgradesPutData = {
  body: Upgrade;
  path?: never;
  query?: never;
  url: "/api/upgrades";
};

export type UpsertUpgradeApiUpgradesPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertUpgradeApiUpgradesPutError =
  UpsertUpgradeApiUpgradesPutErrors[keyof UpsertUpgradeApiUpgradesPutErrors];

export type UpsertUpgradeApiUpgradesPutResponses = {
  /**
   * Successful Response
   */
  200: Upgrade;
};

export type UpsertUpgradeApiUpgradesPutResponse =
  UpsertUpgradeApiUpgradesPutResponses[keyof UpsertUpgradeApiUpgradesPutResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};
