// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client as _heyApiClient } from "../client.gen";
import {
  getPaywallApiPaywallGet,
  listAccountsApiAccountsGet,
  listPricesApiPricesGet,
  listQuotasApiQuotasGet,
  listSubscriptionsApiSubscriptionsGet,
  listUpgradesApiUpgradesGet,
  listUsageEventsApiUsageEventsGet,
  listUsagesApiUsagesGet,
  openCheckoutApiCheckoutGet,
  openCustomerPortalApiCustomerPortalGet,
  type Options,
  reportMeterEventsApiMeterEventsPost,
  upsertAccountApiAccountsPut,
  upsertPriceApiPricesPut,
  upsertQuotaApiQuotasPut,
  upsertSubscriptionApiSubscriptionsPut,
  upsertUpgradeApiUpgradesPut,
  upsertUsageEventApiUsageEventsPost,
} from "../sdk.gen";
import type {
  GetPaywallApiPaywallGetData,
  ListAccountsApiAccountsGetData,
  ListPricesApiPricesGetData,
  ListQuotasApiQuotasGetData,
  ListSubscriptionsApiSubscriptionsGetData,
  ListUpgradesApiUpgradesGetData,
  ListUsageEventsApiUsageEventsGetData,
  ListUsagesApiUsagesGetData,
  OpenCheckoutApiCheckoutGetData,
  OpenCustomerPortalApiCustomerPortalGetData,
  ReportMeterEventsApiMeterEventsPostData,
  ReportMeterEventsApiMeterEventsPostError,
  UpsertAccountApiAccountsPutData,
  UpsertAccountApiAccountsPutError,
  UpsertAccountApiAccountsPutResponse,
  UpsertPriceApiPricesPutData,
  UpsertPriceApiPricesPutError,
  UpsertPriceApiPricesPutResponse,
  UpsertQuotaApiQuotasPutData,
  UpsertQuotaApiQuotasPutError,
  UpsertQuotaApiQuotasPutResponse,
  UpsertSubscriptionApiSubscriptionsPutData,
  UpsertSubscriptionApiSubscriptionsPutError,
  UpsertSubscriptionApiSubscriptionsPutResponse,
  UpsertUpgradeApiUpgradesPutData,
  UpsertUpgradeApiUpgradesPutError,
  UpsertUpgradeApiUpgradesPutResponse,
  UpsertUsageEventApiUsageEventsPostData,
  UpsertUsageEventApiUsageEventsPostError,
  UpsertUsageEventApiUsageEventsPostResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listAccountsApiAccountsGetQueryKey = (
  options?: Options<ListAccountsApiAccountsGetData>,
) => createQueryKey("listAccountsApiAccountsGet", options);

/**
 * List Accounts
 */
export const listAccountsApiAccountsGetOptions = (
  options?: Options<ListAccountsApiAccountsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAccountsApiAccountsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAccountsApiAccountsGetQueryKey(options),
  });
};

/**
 * Upsert Account
 */
export const upsertAccountApiAccountsPutMutation = (
  options?: Partial<Options<UpsertAccountApiAccountsPutData>>,
): UseMutationOptions<
  UpsertAccountApiAccountsPutResponse,
  UpsertAccountApiAccountsPutError,
  Options<UpsertAccountApiAccountsPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertAccountApiAccountsPutResponse,
    UpsertAccountApiAccountsPutError,
    Options<UpsertAccountApiAccountsPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertAccountApiAccountsPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const openCheckoutApiCheckoutGetQueryKey = (
  options: Options<OpenCheckoutApiCheckoutGetData>,
) => createQueryKey("openCheckoutApiCheckoutGet", options);

/**
 * Open Checkout
 */
export const openCheckoutApiCheckoutGetOptions = (
  options: Options<OpenCheckoutApiCheckoutGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openCheckoutApiCheckoutGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: openCheckoutApiCheckoutGetQueryKey(options),
  });
};

export const openCustomerPortalApiCustomerPortalGetQueryKey = (
  options: Options<OpenCustomerPortalApiCustomerPortalGetData>,
) => createQueryKey("openCustomerPortalApiCustomerPortalGet", options);

/**
 * Open Customer Portal
 */
export const openCustomerPortalApiCustomerPortalGetOptions = (
  options: Options<OpenCustomerPortalApiCustomerPortalGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openCustomerPortalApiCustomerPortalGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: openCustomerPortalApiCustomerPortalGetQueryKey(options),
  });
};

export const reportMeterEventsApiMeterEventsPostQueryKey = (
  options?: Options<ReportMeterEventsApiMeterEventsPostData>,
) => createQueryKey("reportMeterEventsApiMeterEventsPost", options);

/**
 * Report Meter Events
 */
export const reportMeterEventsApiMeterEventsPostOptions = (
  options?: Options<ReportMeterEventsApiMeterEventsPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await reportMeterEventsApiMeterEventsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: reportMeterEventsApiMeterEventsPostQueryKey(options),
  });
};

/**
 * Report Meter Events
 */
export const reportMeterEventsApiMeterEventsPostMutation = (
  options?: Partial<Options<ReportMeterEventsApiMeterEventsPostData>>,
): UseMutationOptions<
  unknown,
  ReportMeterEventsApiMeterEventsPostError,
  Options<ReportMeterEventsApiMeterEventsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ReportMeterEventsApiMeterEventsPostError,
    Options<ReportMeterEventsApiMeterEventsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await reportMeterEventsApiMeterEventsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPaywallApiPaywallGetQueryKey = (
  options: Options<GetPaywallApiPaywallGetData>,
) => createQueryKey("getPaywallApiPaywallGet", options);

/**
 * Get Paywall
 */
export const getPaywallApiPaywallGetOptions = (
  options: Options<GetPaywallApiPaywallGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPaywallApiPaywallGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPaywallApiPaywallGetQueryKey(options),
  });
};

export const listPricesApiPricesGetQueryKey = (
  options?: Options<ListPricesApiPricesGetData>,
) => createQueryKey("listPricesApiPricesGet", options);

/**
 * List Prices
 */
export const listPricesApiPricesGetOptions = (
  options?: Options<ListPricesApiPricesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPricesApiPricesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPricesApiPricesGetQueryKey(options),
  });
};

/**
 * Upsert Price
 */
export const upsertPriceApiPricesPutMutation = (
  options?: Partial<Options<UpsertPriceApiPricesPutData>>,
): UseMutationOptions<
  UpsertPriceApiPricesPutResponse,
  UpsertPriceApiPricesPutError,
  Options<UpsertPriceApiPricesPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertPriceApiPricesPutResponse,
    UpsertPriceApiPricesPutError,
    Options<UpsertPriceApiPricesPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertPriceApiPricesPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listQuotasApiQuotasGetQueryKey = (
  options?: Options<ListQuotasApiQuotasGetData>,
) => createQueryKey("listQuotasApiQuotasGet", options);

/**
 * List Quotas
 */
export const listQuotasApiQuotasGetOptions = (
  options?: Options<ListQuotasApiQuotasGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listQuotasApiQuotasGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listQuotasApiQuotasGetQueryKey(options),
  });
};

/**
 * Upsert Quota
 */
export const upsertQuotaApiQuotasPutMutation = (
  options?: Partial<Options<UpsertQuotaApiQuotasPutData>>,
): UseMutationOptions<
  UpsertQuotaApiQuotasPutResponse,
  UpsertQuotaApiQuotasPutError,
  Options<UpsertQuotaApiQuotasPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertQuotaApiQuotasPutResponse,
    UpsertQuotaApiQuotasPutError,
    Options<UpsertQuotaApiQuotasPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertQuotaApiQuotasPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listSubscriptionsApiSubscriptionsGetQueryKey = (
  options?: Options<ListSubscriptionsApiSubscriptionsGetData>,
) => createQueryKey("listSubscriptionsApiSubscriptionsGet", options);

/**
 * List Subscriptions
 */
export const listSubscriptionsApiSubscriptionsGetOptions = (
  options?: Options<ListSubscriptionsApiSubscriptionsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSubscriptionsApiSubscriptionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSubscriptionsApiSubscriptionsGetQueryKey(options),
  });
};

/**
 * Upsert Subscription
 */
export const upsertSubscriptionApiSubscriptionsPutMutation = (
  options?: Partial<Options<UpsertSubscriptionApiSubscriptionsPutData>>,
): UseMutationOptions<
  UpsertSubscriptionApiSubscriptionsPutResponse,
  UpsertSubscriptionApiSubscriptionsPutError,
  Options<UpsertSubscriptionApiSubscriptionsPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertSubscriptionApiSubscriptionsPutResponse,
    UpsertSubscriptionApiSubscriptionsPutError,
    Options<UpsertSubscriptionApiSubscriptionsPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertSubscriptionApiSubscriptionsPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listUsagesApiUsagesGetQueryKey = (
  options?: Options<ListUsagesApiUsagesGetData>,
) => createQueryKey("listUsagesApiUsagesGet", options);

/**
 * List Usages
 */
export const listUsagesApiUsagesGetOptions = (
  options?: Options<ListUsagesApiUsagesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsagesApiUsagesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUsagesApiUsagesGetQueryKey(options),
  });
};

export const listUsageEventsApiUsageEventsGetQueryKey = (
  options?: Options<ListUsageEventsApiUsageEventsGetData>,
) => createQueryKey("listUsageEventsApiUsageEventsGet", options);

/**
 * List Usage Events
 */
export const listUsageEventsApiUsageEventsGetOptions = (
  options?: Options<ListUsageEventsApiUsageEventsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsageEventsApiUsageEventsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUsageEventsApiUsageEventsGetQueryKey(options),
  });
};

export const upsertUsageEventApiUsageEventsPostQueryKey = (
  options: Options<UpsertUsageEventApiUsageEventsPostData>,
) => createQueryKey("upsertUsageEventApiUsageEventsPost", options);

/**
 * Upsert Usage Event
 */
export const upsertUsageEventApiUsageEventsPostOptions = (
  options: Options<UpsertUsageEventApiUsageEventsPostData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await upsertUsageEventApiUsageEventsPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: upsertUsageEventApiUsageEventsPostQueryKey(options),
  });
};

/**
 * Upsert Usage Event
 */
export const upsertUsageEventApiUsageEventsPostMutation = (
  options?: Partial<Options<UpsertUsageEventApiUsageEventsPostData>>,
): UseMutationOptions<
  UpsertUsageEventApiUsageEventsPostResponse,
  UpsertUsageEventApiUsageEventsPostError,
  Options<UpsertUsageEventApiUsageEventsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertUsageEventApiUsageEventsPostResponse,
    UpsertUsageEventApiUsageEventsPostError,
    Options<UpsertUsageEventApiUsageEventsPostData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertUsageEventApiUsageEventsPost({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listUpgradesApiUpgradesGetQueryKey = (
  options?: Options<ListUpgradesApiUpgradesGetData>,
) => createQueryKey("listUpgradesApiUpgradesGet", options);

/**
 * List Upgrades
 */
export const listUpgradesApiUpgradesGetOptions = (
  options?: Options<ListUpgradesApiUpgradesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUpgradesApiUpgradesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUpgradesApiUpgradesGetQueryKey(options),
  });
};

/**
 * Upsert Upgrade
 */
export const upsertUpgradeApiUpgradesPutMutation = (
  options?: Partial<Options<UpsertUpgradeApiUpgradesPutData>>,
): UseMutationOptions<
  UpsertUpgradeApiUpgradesPutResponse,
  UpsertUpgradeApiUpgradesPutError,
  Options<UpsertUpgradeApiUpgradesPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpsertUpgradeApiUpgradesPutResponse,
    UpsertUpgradeApiUpgradesPutError,
    Options<UpsertUpgradeApiUpgradesPutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await upsertUpgradeApiUpgradesPut({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
