// This file is auto-generated by @hey-api/openapi-ts

/**
 * Account
 * A billing account.
 */
export type Account = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Domains
   */
  domains?: Array<string>;
  /**
   * Id
   */
  id?: string;
  /**
   * Members
   */
  members?: Array<string>;
  /**
   * Name
   */
  name: string;
  /**
   * Owner
   */
  owner: string;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Stripe Customer Id
   */
  stripe_customer_id?: string;
};

/**
 * Body_copy_items_api_store_copy_items_post
 */
export type BodyCopyItemsApiStoreCopyItemsPost = {
  /**
   * Source Key
   */
  source_key: {
    [key: string]: unknown;
  };
  /**
   * Target Key
   */
  target_key: {
    [key: string]: unknown;
  };
};

/**
 * Comment
 * A piece of user-provided feedback.
 */
export type Comment = {
  /**
   * Attached Slot Ids
   */
  attached_slot_ids?: Array<string>;
  created_by?: Identity | null;
  /**
   * Id
   */
  id: string;
  /**
   * Images
   */
  images: Array<ImageContent>;
  /**
   * Is Deleted
   */
  is_deleted: boolean;
  /**
   * Is Editable
   */
  is_editable: boolean;
  /**
   * Is Submitted
   */
  is_submitted: boolean;
  message: TextContent;
  screenshot?: ImageContent | null;
  /**
   * Source
   */
  source?: "user" | "ai";
  /**
   * Thread Id
   */
  thread_id?: string | null;
  /**
   * X
   */
  x: number;
  /**
   * Y
   */
  y: number;
};

/**
 * CommentDependency
 */
export type CommentDependency = {
  /**
   * Comment Id
   * Comment that must be included as context.
   */
  comment_id: string;
  /**
   * Type
   */
  type?: "comment_dependency";
};

/**
 * ContentType
 */
export type ContentType = "image" | "text";

/**
 * Element
 * An element that is displayed on the canvas.
 */
export type ElementInput = {
  /**
   * Annotations
   */
  annotations?: Array<
    {
      type: "suggested_flows_annotation";
    } & SuggestedFlowsAnnotation
  >;
  /**
   * Content
   */
  content?:
    | (
        | ({
            type: "text";
          } & TextContent)
        | ({
            type: "image";
          } & ImageContent)
      )
    | null;
  slot: Slot;
};

/**
 * Element
 * An element that is displayed on the canvas.
 */
export type ElementOutput = {
  /**
   * Annotations
   */
  annotations?: Array<
    {
      type: "suggested_flows_annotation";
    } & SuggestedFlowsAnnotation
  >;
  /**
   * Content
   */
  content?:
    | (
        | ({
            type: "text";
          } & TextContent)
        | ({
            type: "image";
          } & ImageContent)
      )
    | null;
  slot: Slot;
};

/**
 * ErrorAgentResponse
 */
export type ErrorAgentResponse = {
  /**
   * Id
   */
  id?: string;
  /**
   * Request Id
   */
  request_id?: string | null;
  /**
   * Type
   */
  type?: "error_agent_response";
  /**
   * Stack Trace
   */
  stack_trace?: string;
  /**
   * Summary
   */
  summary?: string;
};

/**
 * GenerateCommentReplyAgentRequest
 */
export type GenerateCommentReplyAgentRequestInput = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "generate_comment_reply_agent_request";
  /**
   * Comment Id
   */
  comment_id: string;
  /**
   * Elements
   */
  elements?: Array<ElementInput>;
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * GenerateCommentReplyAgentRequest
 */
export type GenerateCommentReplyAgentRequestOutput = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "generate_comment_reply_agent_request";
  /**
   * Comment Id
   */
  comment_id: string;
  /**
   * Elements
   */
  elements?: Array<ElementOutput>;
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * GenerateCommentReplyAgentResponse
 */
export type GenerateCommentReplyAgentResponse = {
  /**
   * Id
   */
  id?: string;
  /**
   * Request Id
   */
  request_id?: string | null;
  /**
   * Type
   */
  type?: "generate_comment_reply_agent_response";
  reply: Comment;
};

/**
 * GenerateRevisionAgentRequest
 */
export type GenerateRevisionAgentRequestInput = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "generate_revision_agent_request";
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Elements
   */
  elements?: Array<ElementInput>;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * GenerateRevisionAgentRequest
 */
export type GenerateRevisionAgentRequestOutput = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "generate_revision_agent_request";
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Elements
   */
  elements?: Array<ElementOutput>;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * GenerateRevisionAgentResponse
 */
export type GenerateRevisionAgentResponse = {
  /**
   * Id
   */
  id?: string;
  /**
   * Request Id
   */
  request_id?: string | null;
  /**
   * Type
   */
  type?: "generate_revision_agent_response";
  /**
   * Slots Reasoning
   */
  slots_reasoning?: {
    [key: string]: Reasoning;
  };
  /**
   * Slots
   */
  slots?: {
    [key: string]: Slot;
  };
  /**
   * Elements Reasoning
   */
  elements_reasoning?: {
    [key: string]: Reasoning;
  };
  /**
   * Elements
   */
  elements?: {
    [key: string]: ElementOutput;
  };
  /**
   * Questions
   */
  questions?: Array<string>;
};

/**
 * GenerateTitleAgentRequest
 */
export type GenerateTitleAgentRequest = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "generate_title_agent_request";
  /**
   * Design Id
   */
  design_id: string;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * GenerateTitleAgentResponse
 */
export type GenerateTitleAgentResponse = {
  /**
   * Id
   */
  id?: string;
  /**
   * Request Id
   */
  request_id?: string | null;
  /**
   * Type
   */
  type?: "generate_title_agent_response";
  /**
   * Design Id
   */
  design_id: string;
  /**
   * Title
   */
  title?: string;
};

/**
 * GenerateUserInputTitleAgentRequest
 */
export type GenerateUserInputTitleAgentRequest = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "generate_user_input_title_agent_request";
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * GenerateUserInputTitleAgentResponse
 */
export type GenerateUserInputTitleAgentResponse = {
  /**
   * Id
   */
  id?: string;
  /**
   * Request Id
   */
  request_id?: string | null;
  /**
   * Type
   */
  type?: "generate_user_input_title_agent_response";
  /**
   * Title
   */
  title?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Identity
 */
export type Identity = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Picture
   */
  picture?: string | null;
};

/**
 * ImageContent
 */
export type ImageContent = {
  /**
   * Is Preview
   * Whether this is a preview image (lower quality, from fast model).
   */
  is_preview?: boolean;
  /**
   * Type
   */
  type?: "image";
  /**
   * Url
   * Image URL.
   */
  url: string;
};

/**
 * Metric
 * A usage-based billing metric.
 */
export type Metric = "projects_created" | "revisions_generated";

/**
 * Paywall
 */
export type Paywall = {
  /**
   * Recommended Upgrades
   */
  recommended_upgrades: Array<RecommendedUpgrade>;
};

/**
 * Period
 * A time interval.
 */
export type Period = {
  /**
   * Starts At
   */
  starts_at: string;
  /**
   * Ends At
   */
  ends_at: string;
};

/**
 * Price
 * A price of a subscription.
 */
export type Price = {
  /**
   * Amount
   */
  amount?: number;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Currency
   */
  currency?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Id
   */
  id?: string;
  /**
   * Stripe Price Id
   */
  stripe_price_id: string;
  /**
   * Stripe Product Id
   */
  stripe_product_id?: string;
};

/**
 * Quota
 * A usage limit.
 */
export type Quota = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Hard Limit
   */
  hard_limit?: number | null;
  /**
   * Id
   */
  id?: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  metric: Metric;
  /**
   * Price Id
   */
  price_id: string;
  /**
   * Soft Limit
   */
  soft_limit?: number | null;
};

/**
 * Reasoning
 */
export type Reasoning = {
  /**
   * Created At
   * Time that generation of the summary began.
   */
  created_at?: string;
  /**
   * Completed At
   * Time that generation of the summary completed.
   */
  completed_at?: string | null;
  /**
   * Id
   * Unique identifier of the summary.
   */
  id?: string;
  /**
   * Summaries
   * Summary of the thought process behind a model output.
   */
  summaries?: {
    [key: string]: string;
  };
};

/**
 * RecommendedUpgrade
 */
export type RecommendedUpgrade = {
  current_usage: Usage;
  upgrade: Upgrade;
  upgrade_price: Price;
  /**
   * Upgrade Quotas
   */
  upgrade_quotas: Array<Quota>;
};

/**
 * RetryContentAgentRequest
 * Request to retry content generation for specific failed slots.
 */
export type RetryContentAgentRequestInput = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "retry_content_agent_request";
  /**
   * Slots
   */
  slots: Array<Slot>;
  /**
   * Elements
   */
  elements?: Array<ElementInput>;
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * RetryContentAgentRequest
 * Request to retry content generation for specific failed slots.
 */
export type RetryContentAgentRequestOutput = {
  /**
   * Id
   */
  id?: string;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Type
   */
  type?: "retry_content_agent_request";
  /**
   * Slots
   */
  slots: Array<Slot>;
  /**
   * Elements
   */
  elements?: Array<ElementOutput>;
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Problem
   */
  problem: Array<
    | ({
        type: "text";
      } & TextContent)
    | ({
        type: "image";
      } & ImageContent)
  >;
};

/**
 * RetryContentAgentResponse
 * Response for retry content generation.
 */
export type RetryContentAgentResponse = {
  /**
   * Id
   */
  id?: string;
  /**
   * Request Id
   */
  request_id?: string | null;
  /**
   * Type
   */
  type?: "retry_content_agent_response";
  /**
   * Slots
   */
  slots?: {
    [key: string]: Slot;
  };
  /**
   * Elements Reasoning
   */
  elements_reasoning?: {
    [key: string]: Reasoning;
  };
  /**
   * Elements
   */
  elements?: {
    [key: string]: ElementOutput;
  };
};

/**
 * Slot
 * A region of the canvas where content is intended to be generated.
 */
export type Slot = {
  /**
   * Type of content that should be displayed in the slot.
   */
  content_type: ContentType;
  /**
   * A description of the image for images and the actual text content for text.
   */
  description: TextContent;
  /**
   * Dependencies
   * Dependencies that must be generated before the content of this slot.
   */
  dependencies?: Array<
    | ({
        type: "comment_dependency";
      } & CommentDependency)
    | ({
        type: "slot_dependency";
      } & SlotDependency)
  >;
  /**
   * Height
   * The height of this slot in pixels.
   */
  height: number;
  /**
   * Id
   * A unique identifier of this slot within the canvas.
   */
  id: string;
  /**
   * Source
   * Whether this slot was created by a user or generated by AI.
   */
  source?: "user" | "ai";
  /**
   * Width
   * The width of this slot in pixels.
   */
  width: number;
  /**
   * X
   * The x-coordinate of the top-left corner of this slot in pixels.
   */
  x: number;
  /**
   * Y
   * The y-coordinate of the top-left corner of this slot in pixels.
   */
  y: number;
};

/**
 * SlotDependency
 */
export type SlotDependency = {
  /**
   * Slot Id
   * Slot that must be generated first.
   */
  slot_id: string;
  /**
   * Type
   */
  type?: "slot_dependency";
};

/**
 * State
 * A versioned key-value pair.
 */
export type State = {
  /**
   * Key
   */
  key: {
    [key: string]: unknown;
  };
  /**
   * Value
   */
  value: unknown;
  /**
   * Version
   */
  version: number;
};

/**
 * Subscription
 * A paid subscription.
 */
export type Subscription = {
  /**
   * Account Id
   */
  account_id: string;
  /**
   * Billing Periods
   */
  billing_periods: Array<Period>;
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Id
   */
  id?: string;
  /**
   * Price Id
   */
  price_id: string;
  /**
   * Status
   */
  status?:
    | "active"
    | "canceled"
    | "incomplete"
    | "incomplete_expired"
    | "past_due"
    | "paused"
    | "trialing"
    | "unpaid";
  /**
   * Stripe Subscription Id
   */
  stripe_subscription_id: string;
  /**
   * Stripe Subscription Item Id
   */
  stripe_subscription_item_id: string;
};

/**
 * SuggestedFlowsAnnotation
 * A list of suggested flows that are displayed on hover.
 */
export type SuggestedFlowsAnnotation = {
  /**
   * Type
   */
  type?: "suggested_flows_annotation";
  /**
   * Suggested Flows
   */
  suggested_flows: Array<string>;
};

/**
 * TextContent
 */
export type TextContent = {
  /**
   * Bold
   * Whether the text should be displayed in bold (600 weight).
   */
  bold?: boolean;
  /**
   * Text
   * Text content.
   */
  text: string;
  /**
   * Type
   */
  type?: "text";
  /**
   * Variant
   * Style in which to display the text.
   */
  variant?: "small" | "p" | "h3" | "h2" | "h1";
};

/**
 * Upgrade
 * A suggested upgrade from one price to another.
 */
export type Upgrade = {
  /**
   * Created At
   */
  created_at?: string;
  /**
   * Current Price Id
   */
  current_price_id?: string | null;
  /**
   * Id
   */
  id?: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Upgrade Price Id
   */
  upgrade_price_id: string;
};

/**
 * Usage
 * Amount of a quota that has been used.
 */
export type Usage = {
  account: Account;
  billing_period: Period;
  metric: Metric;
  price: Price;
  quota: Quota | null;
  subscription: Subscription;
  /**
   * Usage
   */
  usage: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type CallApiAgentCallPostData = {
  /**
   * Request
   */
  body:
    | ({
        type: "generate_revision_agent_request";
      } & GenerateRevisionAgentRequestInput)
    | ({
        type: "generate_title_agent_request";
      } & GenerateTitleAgentRequest)
    | ({
        type: "generate_user_input_title_agent_request";
      } & GenerateUserInputTitleAgentRequest)
    | ({
        type: "retry_content_agent_request";
      } & RetryContentAgentRequestInput)
    | ({
        type: "generate_comment_reply_agent_request";
      } & GenerateCommentReplyAgentRequestInput);
  path?: never;
  query?: never;
  url: "/api/agent/call";
};

export type CallApiAgentCallPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CallApiAgentCallPostError =
  CallApiAgentCallPostErrors[keyof CallApiAgentCallPostErrors];

export type CallApiAgentCallPostResponses = {
  /**
   * Response Call Api Agent Call Post
   * Successful Response
   */
  200:
    | ({
        type: "generate_revision_agent_request";
      } & GenerateRevisionAgentRequestOutput)
    | ({
        type: "generate_title_agent_request";
      } & GenerateTitleAgentRequest)
    | ({
        type: "generate_user_input_title_agent_request";
      } & GenerateUserInputTitleAgentRequest)
    | ({
        type: "retry_content_agent_request";
      } & RetryContentAgentRequestOutput)
    | ({
        type: "generate_comment_reply_agent_request";
      } & GenerateCommentReplyAgentRequestOutput);
};

export type CallApiAgentCallPostResponse =
  CallApiAgentCallPostResponses[keyof CallApiAgentCallPostResponses];

export type GetResponsesApiAgentResponsesGetGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Request Id
     */
    request_id: string;
  };
  url: "/api/agent/responses/get";
};

export type GetResponsesApiAgentResponsesGetGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetResponsesApiAgentResponsesGetGetError =
  GetResponsesApiAgentResponsesGetGetErrors[keyof GetResponsesApiAgentResponsesGetGetErrors];

export type GetResponsesApiAgentResponsesGetGetResponses = {
  /**
   * Response Get Responses Api Agent Responses Get Get
   * Successful Response
   */
  200: Array<
    | ({
        type: "error_agent_response";
      } & ErrorAgentResponse)
    | ({
        type: "generate_revision_agent_response";
      } & GenerateRevisionAgentResponse)
    | ({
        type: "generate_title_agent_response";
      } & GenerateTitleAgentResponse)
    | ({
        type: "generate_user_input_title_agent_response";
      } & GenerateUserInputTitleAgentResponse)
    | ({
        type: "retry_content_agent_response";
      } & RetryContentAgentResponse)
    | ({
        type: "generate_comment_reply_agent_response";
      } & GenerateCommentReplyAgentResponse)
  >;
};

export type GetResponsesApiAgentResponsesGetGetResponse =
  GetResponsesApiAgentResponsesGetGetResponses[keyof GetResponsesApiAgentResponsesGetGetResponses];

export type StreamResponsesApiAgentResponsesStreamGetData = {
  body?: never;
  headers?: {
    /**
     * Last-Event-Id
     */
    "last-event-id"?: string | null;
  };
  path?: never;
  query: {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Last Event Id
     */
    last_event_id?: string | null;
  };
  url: "/api/agent/responses/stream";
};

export type StreamResponsesApiAgentResponsesStreamGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StreamResponsesApiAgentResponsesStreamGetError =
  StreamResponsesApiAgentResponsesStreamGetErrors[keyof StreamResponsesApiAgentResponsesStreamGetErrors];

export type StreamResponsesApiAgentResponsesStreamGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPaywallApiBillingPaywallGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/billing/paywall";
};

export type GetPaywallApiBillingPaywallGetResponses = {
  /**
   * Response Get Paywall Api Billing Paywall Get
   * Successful Response
   */
  200: Paywall | null;
};

export type GetPaywallApiBillingPaywallGetResponse =
  GetPaywallApiBillingPaywallGetResponses[keyof GetPaywallApiBillingPaywallGetResponses];

export type OpenCheckoutApiBillingCheckoutPostData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Cancel Url
     */
    cancel_url: string;
    /**
     * Price Id
     */
    price_id: string;
    /**
     * Success Url
     */
    success_url: string;
  };
  url: "/api/billing/checkout";
};

export type OpenCheckoutApiBillingCheckoutPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpenCheckoutApiBillingCheckoutPostError =
  OpenCheckoutApiBillingCheckoutPostErrors[keyof OpenCheckoutApiBillingCheckoutPostErrors];

export type OpenCheckoutApiBillingCheckoutPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OpenCustomerPortalApiBillingCustomerPortalPostData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Return Url
     */
    return_url: string;
  };
  url: "/api/billing/customer-portal";
};

export type OpenCustomerPortalApiBillingCustomerPortalPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OpenCustomerPortalApiBillingCustomerPortalPostError =
  OpenCustomerPortalApiBillingCustomerPortalPostErrors[keyof OpenCustomerPortalApiBillingCustomerPortalPostErrors];

export type OpenCustomerPortalApiBillingCustomerPortalPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CopyItemsApiStoreCopyItemsPostData = {
  body: BodyCopyItemsApiStoreCopyItemsPost;
  path?: never;
  query?: never;
  url: "/api/store/copy-items";
};

export type CopyItemsApiStoreCopyItemsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CopyItemsApiStoreCopyItemsPostError =
  CopyItemsApiStoreCopyItemsPostErrors[keyof CopyItemsApiStoreCopyItemsPostErrors];

export type CopyItemsApiStoreCopyItemsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetItemApiStoreGetItemPostData = {
  /**
   * Key
   */
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/api/store/get-item";
};

export type GetItemApiStoreGetItemPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetItemApiStoreGetItemPostError =
  GetItemApiStoreGetItemPostErrors[keyof GetItemApiStoreGetItemPostErrors];

export type GetItemApiStoreGetItemPostResponses = {
  /**
   * Successful Response
   */
  200: State;
};

export type GetItemApiStoreGetItemPostResponse =
  GetItemApiStoreGetItemPostResponses[keyof GetItemApiStoreGetItemPostResponses];

export type ListItemsApiStoreListItemsPostData = {
  /**
   * Key
   */
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/api/store/list-items";
};

export type ListItemsApiStoreListItemsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListItemsApiStoreListItemsPostError =
  ListItemsApiStoreListItemsPostErrors[keyof ListItemsApiStoreListItemsPostErrors];

export type ListItemsApiStoreListItemsPostResponses = {
  /**
   * Response List Items Api Store List Items Post
   * Successful Response
   */
  200: Array<State>;
};

export type ListItemsApiStoreListItemsPostResponse =
  ListItemsApiStoreListItemsPostResponses[keyof ListItemsApiStoreListItemsPostResponses];

export type SetItemApiStoreSetItemPutData = {
  body: State;
  path?: never;
  query?: never;
  url: "/api/store/set-item";
};

export type SetItemApiStoreSetItemPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetItemApiStoreSetItemPutError =
  SetItemApiStoreSetItemPutErrors[keyof SetItemApiStoreSetItemPutErrors];

export type SetItemApiStoreSetItemPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RemoveItemApiStoreRemoveItemDeleteData = {
  /**
   * Key
   */
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/api/store/remove-item";
};

export type RemoveItemApiStoreRemoveItemDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveItemApiStoreRemoveItemDeleteError =
  RemoveItemApiStoreRemoveItemDeleteErrors[keyof RemoveItemApiStoreRemoveItemDeleteErrors];

export type RemoveItemApiStoreRemoveItemDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};
